### ISSUE TITLE
Exif DateTime is not setting correctly

### ISSUE THREAD

**Issue by koushikmakam89** [dsoprea/go-exif#14]
I am trying to update the DateTime Exif property of an image , i used the code sample what was provided by you

It seems to not update the DateTime correctly, below is the code spinet from my code base

	// Parse the image.
	jmp := jpeg.NewJpegMediaParser()

	sl, err := jmp.ParseFile(filepath)
	es.ThrowIf(err)

	// Update the UserComment tag.
	rootIb, err := sl.ConstructExifBuilder()
	es.ThrowIf(err)
	ifdPath := "IFD0"

	ifdIb, err := exif.GetOrCreateIbFromRootIb(rootIb, ifdPath)
	es.ThrowIf(err)

	now := time.Now().UTC()
	updatedTimestampPhrase := exif.ExifFullTimestampString(now)
	log.Printf("time stamp %s", updatedTimestampPhrase)

	err = ifdIb.SetStandardWithName("DateTime", updatedTimestampPhrase)
	es.ThrowIf(err)

	// Update the exif segment.

	err = sl.SetExif(rootIb)
	es.ThrowIf(err)

	b := new(bytes.Buffer)

	err = sl.Write(b)
	es.ThrowIf(err)

	updatedImageBytes := b.Bytes()
	//updatedImageBytes = updatedImageBytes
	ioutil.WriteFile(path.Join(assetsPath, "good", "updated.jpg"), updatedImageBytes, 0644)

The original image information ![image](https://user-images.githubusercontent.com/28649839/55140216-8663b300-515d-11e9-9618-2128d9484d25.png)

The updated image with new datetime 
![image](https://user-images.githubusercontent.com/28649839/55140262-a09d9100-515d-11e9-9d9e-56355b654afb.png)

If you see the properties is seems to have corrupted the exif 

Do let me know what i am doing wrong

Thanks in advance
Koushik

**Comment by dsoprea** [comment]
What does `log.Printf("time stamp %s", updatedTimestampPhrase)` print?

**Comment by dsoprea** [comment]
Please confirm that you still have the problem and then attach the image with the malformed information to this issue so that I can investigate.

**Comment by koushikmakam89** [comment]
Sorry for the late response , log.Printf("time stamp %s", updatedTimestampPhrase) is printing the datetime in the below format : YYYY:MM:DD HH:MM:SS

**Comment by dsoprea** [comment]
I'm asking for the actual output, please.

**Comment by dsoprea** [comment]
Please confirm fix.
