### ISSUE TITLE
panic: no exif data [recovered]  

### ISSUE THREAD

**Issue by mrold** [dsoprea/go-exif#15]
![image](https://user-images.githubusercontent.com/9475864/55768038-cb68dd00-5aad-11e9-8501-415fa688b515.png)

This image is generated with the go code, so there is no extra information？Is that possible just like a Hash-Map,  and then we can just do like  "get" , "put"  and "delete"?

**Comment by dsoprea** [comment]
You're calling `SearchFileAndExtractExif`, and you're getting a `ErrNoExif` ("no exif data") panic. There's no EXIF data. What extra information were you hoping for?

**Comment by dsoprea** [comment]
Feel free to include the image or your code if you want further support.
