### ISSUE TITLE
Cannot Extract EXIF From PNG

### ISSUE THREAD

**Issue by keithwoelke** [dsoprea/go-exif#19]
I have tried to add EXIF information to a PNG image, but it does not seem parseable by go-exif. I'm not sure how to confirm if this is an issue with how the data is being written to the file or with how go-exif is reading from the file.

[2x2.png (After)](https://user-images.githubusercontent.com/469790/59881044-770e9300-9363-11e9-9fee-2956e4be1524.png)

It's parseable by some online viewers, which say they are parsing the EXIF, such as http://metapicz.com/#landing?imgsrc=https%3A%2F%2Fuser-images.githubusercontent.com%2F469790%2F59881044-770e9300-9363-11e9-9fee-2956e4be1524.png

**Comment by dsoprea** [comment]
The PNG WG and I will look into it.
It was a collaboration. Can you put your before and after images online
somewhere where I can download them?

**Comment by keithwoelke** [comment]
The after is at the link above 2x2.png. The before is here:

[2x2.png (Before)](https://user-images.githubusercontent.com/469790/59882764-fa31e800-9367-11e9-9f93-90552d347861.png)

Is this OK?

**Comment by keithwoelke** [comment]
After doing a binary comparison, it looks like it may be using XMP Tags instead of EXIF Tags which I assume go-exif won't find. Do you have any recommended way of writing actual EXIF data to a PNG image?

**Comment by dsoprea** [comment]
Your link wasn't showing up in the email.

That could be. You can use [go-png-image-structure](https://godoc.org/github.com/dsoprea/go-png-image-structure), a frontend I wrote just to be able to set/get EXIF from PNGs. The underlying reason that I even wrote EXIF, aside from the fun of doing it, was specifically to support PNGs.

https://godoc.org/github.com/dsoprea/go-png-image-structure#example-ChunkSlice-SetExif
