### ISSUE TITLE
Where does the "IsExif" method come from?

### ISSUE THREAD

**Issue by BrianLeishman** [dsoprea/go-exif#2]
In that example snippet, there's this

```
for i := 0; i < len(data); i++ {
    if e.IsExif(data[i:i + 6]) == true {
        foundAt = i
        break
    }
}
```

But what is `e`? 

I've searched the source for `IsExif` and I can't find that function anywhere

**Comment by dsoprea** [comment]
`e` with an `Exif` object, which doesn't exist any more. I had renamed `IsExif()` to `SearchAndExtractExif()` (exif.go) and just put them as functions at the package level (no longer implemented as methods). I had forgotten to update the README, but the GoDoc page should [obviously] be exactly accurate. It's updated with every commit and the testable-examples are built as part of the CI process.

I've updated the README. Should work now but I can't currently test it: https://github.com/dsoprea/go-exif/commit/a5784ff65359b3181c05b7543e758b21dbae56b4#diff-04c6e90faac2675aa89e2176d2eec7d8
