### ISSUE TITLE
tag value read incomplete

### ISSUE THREAD

**Issue by satbirdd** [dsoprea/go-exif#24]
I'am trying to read and modify exif data, and store it back to jpg files. And i found that after getting the ifdBuilder, even if i did not change anything,  when i store it back, the tags'value has been changed. The value lost 6 byte data which is at the very beginning of the original value.
here is my codes:
```
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"

	exif "github.com/dsoprea/go-exif"
	jpegStruct "github.com/dsoprea/go-jpeg-image-structure"
)

// CheckExifReader sets the EXIF DateTime to the given Time unless it has
// already been defined.
func CheckExifReader(filepath string) error {
	parser := jpegStruct.NewJpegMediaParser()
	sl, err := parser.ParseFile(filepath)
	if err != nil {
		return fmt.Errorf("failed to parse JPEG file: %v", err)
	}

	rootIb, err := sl.ConstructExifBuilder()
	if err != nil {
		log.Println("No EXIF; creating it from scratch")

		//TODO what is wrong with this - no EXIF data end up in the JPEG
		im := exif.NewIfdMappingWithStandard()
		ti := exif.NewTagIndex()
		if err := exif.LoadStandardTags(ti); err != nil {
			return fmt.Errorf("failed to load standard tags: %v", err)
		}

		rootIb = exif.NewIfdBuilder(im, ti, exif.IfdPathStandard,
			exif.EncodeDefaultByteOrder)
		rootIb.AddStandardWithName("ProcessingSoftware", "photos-uploader")
	}

	// Update the exif segment.
	if err := sl.SetExif(rootIb); err != nil {
		return fmt.Errorf("failed to set EXIF to jpeg: %v", err)
	}

	// Write the modified file
	b := new(bytes.Buffer)
	if err := sl.Write(b); err != nil {
		return fmt.Errorf("failed to create JPEG data: %v", err)
	}

	filepath = "../data/output_image01.jpg"

	// Save the file
	if err := ioutil.WriteFile(filepath, b.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write JPEG file: %v", err)
	}

	fmt.Printf("Wrote %v\n", filepath)

	return nil
}

func main() {
	err := CheckExifReader("../data/image_01.jpg")
        if err != nil {
	     fmt.Printf("error: %v", err)
        }
}
```
For example, the original exif Model tag's value is "Redmi Note 5A", after i run the program, it become "Note 5A".
However, If change file ifd_tag_entry.go line 139
```value, err = tt.ParseBytes(addressableData[ite.ValueOffset:], byteCount)```
to
```value, err = tt.ParseBytes(addressableData[ite.ValueOffset-6:], byteCount)```
everything will be fine, except some unit test will fail. But that not the right way to do it, and i checked some codes, still did't get a clue. Any solutions?

**Comment by satbirdd** [comment]
my test image file:
![image_01](https://user-images.githubusercontent.com/1664865/65155119-3d7f1e00-da5f-11e9-9792-3902ebf2224e.jpg)

**Comment by dsoprea** [comment]
Resolved by https://github.com/dsoprea/go-exif/commit/9946007f059e3d0b958efec2c67e1db1b02695a6 . See #14.
