### ISSUE TITLE
How to set GPSLatitude and GPSLongitude values

### ISSUE THREAD

**Issue by peternoordijk** [dsoprea/go-exif#32]
I'm trying to set the latitude and longitude (and their refs) correctly. However I'm not really sure about what kind of data I need to convert it to.

For example I use the the following code to convert `lat float64` to something like `52/1 22/1 1332/100`:

```go
latitudeRef := "N"
if lat < 0 {
	latitudeRef = "S"
	lat = -lat
}
degrees := int(math.Floor(lat))
minutes := int(math.Floor(math.Mod(lat*60, 60)))
seconds := int(math.Floor(math.Mod(lat*3600, 3600)))
val := fmt.Sprintf("%d/1 %d/1 %d/100", degrees, minutes, seconds)
```

Then I'm trying to update the exif data with this value like so:

```go
ifdGPSInfo, err := exif.GetOrCreateIbFromRootIb(rootIb, "IFD/GPSInfo")
if err != nil {
	return err
}

err = ifdGPSInfo.SetStandardWithName("GPSLatitudeRef", latitudeRef)
if err != nil {
	return err
}

err = ifdGPSInfo.SetStandardWithName("GPSLatitude", val)
if err != nil {
	return err
}
```

But I'm getting this error:

```
panic: tag (0x0002) value of (19) bytes not evenly divisible by type-size (8)
```

Which makes sense since I guess I shouldn't be using a string value. So my question is, what should I use instead?

I notices the [GpsDegrees](https://godoc.org/github.com/dsoprea/go-exif/v2#GpsDegrees) struct, which I guess has something to do with this... However I didn't find any information on how to use it.

**Comment by dsoprea** [comment]
This should help:

https://godoc.org/github.com/dsoprea/go-exif/v2#example-IfdBuilder-SetStandardWithName-UpdateGps

Sorry for the delay.
