### ISSUE TITLE
runtime.boundsError runtime error: slice bounds out of range [:8] with capacity 4

### ISSUE THREAD

**Issue by matchstick** [dsoprea/go-exif#33]
Ran exif-read-tool on my photo corpus. There are about 100K files. Several of them from a Canon EOS 5D Mark II that were taken in 2011 cannot be processed. They show the following error. 

I can provide photo but would prefer to not attach in bug as it is a picture of some one I cannot get permission from anymore. Thanks in advance 

Program error.
Stack:

runtime.boundsError runtime error: slice bounds out of range [:8] with capacity 4
/home/mhr/go/src/github.com/dsoprea/go-exif/v2/undefined/exif_9286_user_comment.go:99 (0x58e632)
/usr/local/go/src/runtime/panic.go:969 (0x431a96)
/usr/local/go/src/runtime/panic.go:106 (0x4300c3)
/home/mhr/go/src/github.com/dsoprea/go-exif/v2/undefined/exif_9286_user_comment.go:113 (0x58a841)
/home/mhr/go/src/github.com/dsoprea/go-exif/v2/undefined/accessor.go:51 (0x587bbf)
/home/mhr/go/src/github.com/dsoprea/go-exif/v2/ifd_tag_entry.go:149 (0x5e2f84)
/home/mhr/go/src/github.com/dsoprea/go-exif/v2/exif-read-tool/main.go:120 (0x5e897a)
/home/mhr/go/src/github.com/dsoprea/go-exif/v2/ifd_enumerate.go:252 (0x5dc40d)
/home/mhr/go/src/github.com/dsoprea/go-exif/v2/ifd_enumerate.go:323 (0x5dcd20)
/home/mhr/go/src/github.com/dsoprea/go-exif/v2/ifd_enumerate.go:263 (0x5dc395)
/home/mhr/go/src/github.com/dsoprea/go-exif/v2/ifd_enumerate.go:323 (0x5dcd20)
/home/mhr/go/src/github.com/dsoprea/go-exif/v2/ifd_enumerate.go:345 (0x5dce5e)
/home/mhr/go/src/github.com/dsoprea/go-exif/v2/exif.go:192 (0x5d86f5)
/home/mhr/go/src/github.com/dsoprea/go-exif/v2/exif-read-tool/main.go:151 (0x5e7e21)
/usr/local/go/src/runtime/proc.go:203 (0x434802)
/usr/local/go/src/runtime/asm_amd64.s:1373 (0x45ee41)

What is the best way to provide version as I don't see a subcommand.
I did the "go get" last night.

**Comment by dsoprea** [comment]
Thanks, Michael. Regarding the version, just share the output of "git log -1".

I'll let you know if I need an image.

**Comment by matchstick** [comment]
You asked for the output of go-exif-knife. It crashes too. Here it is:

Stack:

runtime.boundsError runtime error: slice bounds out of range [:8] with capacity 4
/home/mhr/go/pkg/mod/github.com/dsoprea/go-exif/v2@v2.0.0-20200321225314-640175a69fe4/undefined/exif_9286_user_comment.go:99 (0x5c2062)
	Codec9286UserComment.Decode.func1: err = log.Wrap(state.(error))
/usr/local/go/src/runtime/panic.go:969 (0x434076)
	gopanic: done = runOpenDeferFrame(gp, d)
/usr/local/go/src/runtime/panic.go:106 (0x432543)
	goPanicSliceAcap: panic(boundsError{x: int64(x), signed: true, y: y, code: boundsSliceAcap})
/home/mhr/go/pkg/mod/github.com/dsoprea/go-exif/v2@v2.0.0-20200321225314-640175a69fe4/undefined/exif_9286_user_comment.go:113 (0x5be271)
	Codec9286UserComment.Decode: encoding := valueBytes[:8]
/home/mhr/go/pkg/mod/github.com/dsoprea/go-exif/v2@v2.0.0-20200321225314-640175a69fe4/undefined/accessor.go:51 (0x5bb5ef)
	Decode: value, err = decoder.Decode(valueContext)
/home/mhr/go/pkg/mod/github.com/dsoprea/go-exif/v2@v2.0.0-20200321225314-640175a69fe4/ifd_tag_entry.go:149 (0x627174)
	(*IfdTagEntry).Value: value, err = exifundefined.Decode(valueContext)
/home/mhr/go/pkg/mod/github.com/dsoprea/go-exif/v2@v2.0.0-20200321225314-640175a69fe4/ifd_tag_entry.go:175 (0x627424)
	(*IfdTagEntry).Format: value, err := ite.Value()
/home/mhr/go/pkg/mod/github.com/dsoprea/go-exif/v2@v2.0.0-20200321225314-640175a69fe4/ifd_enumerate.go:559 (0x621f65)
	(*Ifd).printTagTree: valuePhrase, err = ite.Format()
/home/mhr/go/pkg/mod/github.com/dsoprea/go-exif/v2@v2.0.0-20200321225314-640175a69fe4/ifd_enumerate.go:577 (0x621cf5)
	(*Ifd).printTagTree: childIfd.printTagTree(populateValues, 0, level+1, false)
/home/mhr/go/pkg/mod/github.com/dsoprea/go-exif/v2@v2.0.0-20200321225314-640175a69fe4/ifd_enumerate.go:592 (0x7caf2e)
	(*ExifRead).Read: ifd.printTagTree(populateValues, 0, 0, false)
/home/mhr/go/pkg/mod/github.com/dsoprea/go-exif/v2@v2.0.0-20200321225314-640175a69fe4/ifd_enumerate.go:592 (0x7caf0b)
	(*Ifd).PrintTagTree: ifd.printTagTree(populateValues, 0, 0, false)
/home/mhr/go/pkg/mod/github.com/dsoprea/go-exif-knife@v0.0.0-20200401235717-11b5b0e33785/command/go-exif-knife/main.go:78 (0x7cd2bf)
	main: err := er.Read(options.Filepath, options.JustTry, options.SpecificIfd, options.SpecificTags, options.JustValues, options.Json)
/usr/local/go/src/runtime/proc.go:203 (0x436de2)
	main: fn()
/usr/local/go/src/runtime/asm_amd64.s:1373 (0x463501)
	goexit: BYTE	$0x90	// NOP

Version is coming.

**Comment by matchstick** [comment]
Version Info is:
f$ git log -1
commit 640175a69fe4582cd8de6605aa39ffc40f65ce2b (HEAD -> master, origin/master, origin/HEAD)
Author: Dustin Oprea <myselfasunder@gmail.com>
Date:   Sat Mar 21 18:53:14 2020 -0400

    exif-read-tool: Skip unsupported undefined tags
$

**Comment by dsoprea** [comment]
Alright. So, we're gonna have to feel around a little. It'd be helpful if you could reproduce this with an image that you can share.

I've added a little verbosity to that code in the `dustin/issue33_buggy_usercomment_byte_length` branch:

https://github.com/dsoprea/go-exif/tree/dustin/issue33_buggy_usercomment_byte_length

```
v2]$ go run exif-read-tool/main.go -filepath assets/NDM_8901.jpg

UserComment: LEN=(264) UNIT-COUNT=(264)
DUMP: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
```

There's no conceivable reason that slice should ever be less than nine bytes. Since I've not encountered an issue there before, I'm guessing that this is just an imperfect value in the image. Needless to say, it'll be a more interesting issue if you tell me that you've seen this issue in multiple places. However, that would likely mean that the same image-source was involved with a buggy/nonconformant implementation of EXIF.

If it turns out to be an image problem, I'll update the _exif-read-tool_ to ignore and note tags that can't be parsed. It'll still be the responsibility of developers to account for this in their own tag processing/printing loops (exif_-read-tool_ is just an example tool for developers to learn from).
