### ISSUE TITLE
GPSVersionID 2.0.0.0

### ISSUE THREAD

**Issue by lastzero** [dsoprea/go-exif#35]
Any reason GPSVersionID 2.0.0.0 is not supported, only 2.2.0.0 and 2.3.0.0?

Didn't find any useful information on how version 2.0 is different from 2.2 or 2.3, coordinates look the same.

See https://github.com/photoprism/photoprism/issues/295

**Comment by dsoprea** [comment]
Supported by what? go-exif? I'm not interpreting the version. I don't remember really being able to find any information on versions at all. I just assumed that it'd be brought to my attention if we suddenly had data or documentation to work from :) .

```
$ go run exif-read-tool/main.go -filepath 81028017-2c3a3300-8ec3-11ea-9e19-f411ac46dc45.jpg 
IFD-PATH=[IFD] ID=(0x0100) NAME=[ImageWidth] COUNT=(1) TYPE=[SLONG] VALUE=[4940]
IFD-PATH=[IFD] ID=(0x0101) NAME=[ImageLength] COUNT=(1) TYPE=[SLONG] VALUE=[3272]
IFD-PATH=[IFD] ID=(0x0112) NAME=[Orientation] COUNT=(1) TYPE=[SHORT] VALUE=[1]
IFD-PATH=[IFD] ID=(0x0131) NAME=[Software] COUNT=(39) TYPE=[ASCII] VALUE=[Perfectly Clear Complete v3 3.6.3.1351]
IFD-PATH=[IFD] ID=(0x8825) NAME=[GPSTag] COUNT=(1) TYPE=[LONG] VALUE=[114]
IFD-PATH=[IFD/GPSInfo] ID=(0x0000) NAME=[GPSVersionID] COUNT=(4) TYPE=[BYTE] VALUE=[02 00 00 00]
IFD-PATH=[IFD/GPSInfo] ID=(0x0001) NAME=[GPSLatitudeRef] COUNT=(2) TYPE=[ASCII] VALUE=[S]
IFD-PATH=[IFD/GPSInfo] ID=(0x0002) NAME=[GPSLatitude] COUNT=(3) TYPE=[RATIONAL] VALUE=[38/1...]
IFD-PATH=[IFD/GPSInfo] ID=(0x0003) NAME=[GPSLongitudeRef] COUNT=(2) TYPE=[ASCII] VALUE=[E]
IFD-PATH=[IFD/GPSInfo] ID=(0x0004) NAME=[GPSLongitude] COUNT=(3) TYPE=[RATIONAL] VALUE=[144/1...]
IFD-PATH=[IFD/GPSInfo] ID=(0x0012) NAME=[GPSMapDatum] COUNT=(7) TYPE=[ASCII] VALUE=[WGS-84]
IFD-PATH=[IFD] ID=(0x0103) NAME=[Compression] COUNT=(1) TYPE=[SHORT] VALUE=[6]
IFD-PATH=[IFD] ID=(0x011a) NAME=[XResolution] COUNT=(1) TYPE=[RATIONAL] VALUE=[0/1]
IFD-PATH=[IFD] ID=(0x011b) NAME=[YResolution] COUNT=(1) TYPE=[RATIONAL] VALUE=[0/1]
IFD-PATH=[IFD] ID=(0x0128) NAME=[ResolutionUnit] COUNT=(1) TYPE=[SHORT] VALUE=[2]
```

Shows up fine for me and the data doesn't appear to be represented any differently than it normally is.

**Comment by dsoprea** [comment]
Coincidentally, I just added some software support, at least one test, and one example for updating GPS last night. It wouldn't hurt to bump your integration.

**Comment by lastzero** [comment]
@dsoprea Already upgraded, I should have been more precise. The raw data is there but `GpsInfo()` returns `ErrNoGpsTags` because GPSVersionID 2.0.0.0 is explicitly not supported:

https://github.com/dsoprea/go-exif/blob/master/v2/ifd_enumerate.go#L30

**Comment by dsoprea** [comment]
You're right. Added support and added a unit-test for 2.0.0.0 support with this specific image.

**Comment by lastzero** [comment]
That was quick! Thanks a lot, I'll test it :)

**Comment by dsoprea** [comment]
Lately there has been a lot of opportunity to fix issues for which there was previously no data or no documentation. For every one issue that's reported, I'd rather not think of how many people might have experienced it and said nothing.

It's my pleasure to fix them.
