### ISSUE TITLE
slice bounds out of range [1380994898:824795]

### ISSUE THREAD

**Issue by matchstick** [dsoprea/go-exif#36]
Trying to help by providing old pics that are causing hiccups for library.

![antique shop](https://user-images.githubusercontent.com/19715963/81146710-a7d0ca00-8f2d-11ea-9192-5c5d5a0af778.jpg)

Hope this is welcome. If not no big deal. 

Other programs on linux and mac can parse the exif data. 

$ git log -1
commit 8da3881353b3c5d851af5f23018edf95db2f5738 (HEAD -> master, origin/master, origin/HEAD)
Author: Dustin Oprea <dustin@randomingenuity.com>
Date:   Wed May 6 01:47:03 2020 -0400

    Fix GPS 2.0.0.0 test image name

**Comment by matchstick** [comment]
Code does not panic just yields error "slice bounds out of range [1380994898:824795] "

**Comment by dsoprea** [comment]
It looks like one of the IFDs (tag tables) points to an invalid offset in the file. I've updated it to just stop parsing at that point. You can see the remark if you pass -verbose into `exif-read-tool`:

```
2020/05/06 04:54:40 exifjpeg.ifd: [WARNING]  Tag in IFD [IFD] at position (10) has invalid type and will be skipped.
2020/05/06 04:54:40 exifjpeg.ifd: [DEBUG]  Next IFD at offset: (52504f52)
2020/05/06 04:54:40 exifjpeg.ifd: [DEBUG]  Parsing IFD [IFD] (1) at offset (52504f52) (scan).
2020/05/06 04:54:40 exifjpeg.ifd: [ERROR]  IFD [IFD] (1) at offset (52504f52) is unreachable. Terminating scan.
IFD-PATH=[IFD] ID=(0x010f) NAME=[Make] COUNT=(18) TYPE=[ASCII] VALUE=[NIKON CORPORATION]
```

**Comment by dsoprea** [comment]
They're quick fixes and I don't like losing momentum with stuff like this.
