### ISSUE TITLE
Support for IPTC and XMP metadata planned?

### ISSUE THREAD

**Issue by curio77** [dsoprea/go-exif#39]
Is it planned to add support for IPTC and XMP metadata to the library (despite its name)? Asking because these three usually have to be dealt with in conjunction, are similar in structure and intention (at least from the end user's point of view), and tools such as *exiftool* support them.

**Comment by dsoprea** [comment]
If there's a need (a standard answer). It would be a separate package,
where there might be an abstraction project that dispatches to them.

@lastzero

**Comment by curio77** [comment]
Thanks!

**Comment by dsoprea** [comment]
I added support for extracting embedded XMP data to go-jpeg-image-structure. It just exposes (and prettifies) the XMP data. There doesn't appear to be a well-support Go project to managing XMP data and I don't want to get sucked into the XML standards at this point. I'll also add support for reading them from PNG (to go-png-image-structure) as well as, probably, writing it once I can find a proper XMP solution that can validate the data (or build one at some point in the future, if I find a month between big things). I'll work on IPTC either just before or just after I add the PNG support.

This is the first commit in the series: https://github.com/dsoprea/go-jpeg-image-structure/commit/b6671f9420bcfcaa35b6cb96defdc6053dcd02da

**Comment by curio77** [comment]
Great! It will be cool to have a comprehensive solution for dealing with the entire mess of image metadata in Go. 😃
