### ISSUE TITLE
Wrong image orientation

### ISSUE THREAD

**Issue by lastzero** [dsoprea/go-exif#40]
Orientation of this image is reported as **6** while it should be **1**, see [internal/meta/exif_test.go#L247](https://github.com/photoprism/photoprism/blob/develop/internal/meta/exif_test.go#L247). Exiftool and other libraries also say it is 1.

![](https://github.com/photoprism/photoprism/raw/develop/internal/meta/testdata/orientation.jpg)

Didn't manage to test with your latest code as the API has changed and I didn't know how to upgrade safely (without accidentally breaking existing functionality), see [internal/meta/exif.go#L148](https://github.com/photoprism/photoprism/blob/develop/internal/meta/exif.go#L148).

**Comment by dsoprea** [comment]
It appears twice, both (1) and (6).

```
$ go run exif-read-tool/main.go -f orientation-issue40.jpg
...
IFD-PATH=[IFD] ID=(0x0112) NAME=[Orientation] COUNT=(1) TYPE=[SHORT] VALUE=[[1]]
...
IFD-PATH=[IFD1] ID=(0x0112) NAME=[Orientation] COUNT=(1) TYPE=[SHORT] VALUE=[[6]]
...
```

The specification doesn't specifically dictate which of the two standard root IFDs should have which standard IFD values. Naturally, the Samsung S5 appears to write two separate values to two separate places. Obviously the image was rotated in an application that only updated one of them.

**Comment by lastzero** [comment]
Thanks! :)

**Comment by mbethke** [comment]
I think overwriting IFD0 tag values with values from the same tag in IFD1 is not correct. https://www.exif.org/Exif2-2.PDF says:
> Attribute information is stored in TIFF structure including a File Header, with a maximum of two IFD (0th IFD, 1st IFD). The 0th IFD records attribute information concerning the compressed image (primary image). The 1st IFD may be used to record a thumbnail image.

My interpretation (which also seems to be the one here: https://www.media.mit.edu/pia/Research/deepview/exif.html and agrees with the output of `exiv2`) is that any tags in IFD1 relate to the thumbnail only while those in IFD0 relate to the main image, so it's a bit weird but completely legitimate to have things like different orientation values in both of them. Think of a program like `jpegtran` that knows how to rotate JPEG data but may not know how to deal with a non-JPEG thumbnail (incidentally I was bitten by this issue when investigating why some of my `jpegautotran`-treated photos are the right orientation in image viewers but wrong in Photoprism).

If the above is correct, tags from IFD1 should simply not be returned at all, or rather only from a separate method that *only* returns thumbnail data.
It seems to me that you can rely on IFD0 data being found before IFD1 data though, so an easy workaround for people still using v2 (@lastzero) would be to just not overwrite any values for tags you have a value already. Something like this in Photoprism maybe?
```diff
diff --git a/internal/meta/exif.go b/internal/meta/exif.go
index 4ac7e5f3..1a5b64a1 100644
--- a/internal/meta/exif.go
+++ b/internal/meta/exif.go
@@ -109,7 +109,9 @@ func Exif(filename string) (data Data, err error) {
                        }

                        if it.Name != "" && valueString != "" {
-                           tags[it.Name] = strings.Split(valueString, "\x00")[0]
+                           if _, exists := tags[it.Name]; !exists {
+                             tags[it.Name] = strings.Split(valueString, "\x00")[0]
+                           }
                        }
                }
```

**Comment by lastzero** [comment]
Thanks for the hint! Should be fixed with these changes:
- https://github.com/photoprism/photoprism/issues/2231
