### ISSUE TITLE
Failed parsing GPS coordinates

### ISSUE THREAD

**Issue by lastzero** [dsoprea/go-exif#43]
There are two example images in our test suite that still cause trouble when [parsing GPS coordinates](https://github.com/photoprism/photoprism/blob/develop/internal/meta/exif.go):

#### 1. [huawei-gps-error.jpg](https://github.com/photoprism/photoprism/raw/develop/internal/meta/testdata/huawei-gps-error.jpg) ####

`runtime error: index out of range [1] with length 1`

This seems to affect a lot of images, also some older ones taken with a Canon EOS 6D. This example was taken with a Huawei P30 phone, so probably not a vendor specific issue.

#### 2. [panorama360.jpg](https://github.com/photoprism/photoprism/raw/develop/internal/meta/testdata/panorama360.jpg) ####

`runtime error: integer divide by zero`

This file is a resized version (using ImageMagick) of a large panorama image attached to this feature request: https://github.com/photoprism/photoprism/issues/352

Otherwise very happy with your libraries. Keep up the great work! Also added the new heic parser and noticed that an old issue with parsing width and height was fixed.

**Comment by dsoprea** [comment]
I fixed this for v3 and backported to v2. I'd encourage you to update to v3. It should be easy/free for you to do so. The only difference might be how you provide the EXIF data to be parsed. The only change that may affect you is that the process starts with an `io.ReadSeeker` rather than a byte-slice.

**Comment by lastzero** [comment]
Thanks, I was going to ask if upgrading is a good idea at this point. When I saw the reader tool in v3 is still using v2, I decided not to upgrade immediately.... was a glitch as it seems :)

**Comment by dsoprea** [comment]
It sure was.

I had such glorious intentions for tonight prior to deciding that it'd be therapeutic to fix your issue and then suddenly lost six-hours updating go-exif <-> go-utility <- [jpeg, png, tiff, heic] <- go-exif-knife.
