### ISSUE TITLE
Where is the release .exe ?

### ISSUE THREAD

**Issue by Catfriend1** [dsoprea/go-exif#46]
Hi,

Where is the release .exe ?

I can't find them on the releases page nor on Travis CI.

Thank you.

**Comment by dsoprea** [comment]
It's a Go library, not an executable.

**Comment by dsoprea** [comment]
Look at go-exif-knife. It uses go-exif and includes a bunch of distributables: https://github.com/dsoprea/go-exif-knife/releases

**Comment by ghost** [comment]
please delete issue
