### ISSUE TITLE
100% CPU usage when parsing JPEG Exif

### ISSUE THREAD

**Issue by lastzero** [dsoprea/go-exif#60]
One of our users came across JPEG files that cause the `Exif()` function to use 100% CPU... might be stuck in an infinite loop somewhere... couldn't find out where yet... hope you can help us with this!

GitHub issue: https://github.com/photoprism/photoprism/issues/1326

Files for debugging: https://github.com/photoprism/photoprism/files/6529695/Pictures.zip

`Exif()` function call in our code: 

https://github.com/photoprism/photoprism/blob/f6c1592cb950f51eda5e1b7e497e8f745ca445cf/internal/meta/exif_parser.go#L38

**Comment by lastzero** [comment]
Reading Exiftool's warning message, it becomes clear why `go-exif` may get stuck in a loop extracting all data:

```
$ exiftool -g yourfile.jpg 
---- ExifTool ----
ExifTool Version Number    : 12.16
Warning                    : IFD1 pointer references previous IFD0 directory
```

Could track it down to `Collect(im, ti, rawExif)` in `github.com/dsoprea/go-exif/v2`, which is used by 

```
github.com/dsoprea/go-jpeg-image-structure v0.0.0-20210512043942-b434301c6836
```

**Comment by dsoprea** [comment]
I've already added handling for cycles in the last year. If you either upgrade to v3 or backport the change to v2 then you might be good.

https://github.com/dsoprea/go-exif/issues/59

**Comment by lastzero** [comment]
Are we using the wrong jpeg structure library then? From what I see, it explicitly depends on go-exif v2

**Comment by dsoprea** [comment]
go-jpeg-image-structure/v2 depends on go-exif/v3.

https://github.com/dsoprea/go-jpeg-image-structure/blob/b434301c683610a9218386e4dada79e03b7aadef/v2/go.mod#L13

**Comment by lastzero** [comment]
Thanks! 👍

**Comment by lastzero** [comment]
Works perfectly 🌈
