### ISSUE TITLE
throw panic "no such file or directory" even if file exist

### ISSUE THREAD

**Issue by Dentrax** [dsoprea/go-exif#61]
Hey, thanks for the cool project!

I have a `test.gif` file in the current directory. Running the following command, throws panic error:

```bash
$ exif-read-tool -filepath test.gif
```

```bash
*fs.PathError open ilepath: no such file or directory
/Users/furkan.turkal/go/pkg/mod/github.com/dsoprea/go-exif/v3@v3.0.0-20210512055020-8213cfabc61b/command/exif-read-tool/main.go:92 (0x11cb177)
	main: log.PanicIf(err)
/usr/local/go/src/runtime/proc.go:225 (0x1037516)
	main: fn()
/usr/local/go/src/runtime/asm_amd64.s:1371 (0x1067c21)
	goexit: BYTE	$0x90	// NOP
```

```
$ open test.gif  # this OK
```

Any ideas? 🤔

**Comment by Dentrax** [comment]
Wow, you are right! In the README, you used `-filepath`, instead of `--filepath`. Two-dashed flags seems to work!

**Comment by dsoprea** [comment]
That was my first assumption, but it still doesn't explain why you got that specific error message.
