### ISSUE TITLE
Can you tag with a Go Modules compatible version tag?

### ISSUE THREAD

**Issue by bep** [dsoprea/go-exif#62]
Seems like Go Modules is very picky about version format, it recognizes `v3.0.0`, but not `3.0.0`.

**Comment by dsoprea** [comment]
Valid point, though I feel like it might be more appropriate to do a major bump to v4.0.0 as an unrecognized/opaque version could be comparatively no different than a backwards-incompatible one. Thoughts?

**Comment by dsoprea** [comment]
I'm currently traveling, so my responses can be delayed and I'll likely take no action in the next week.

**Comment by bep** [comment]
>Thoughts?

A major bump would require a new "path update" (/v4), or whatever Go Modules calls it ... I would have just duplicated the tag, as both would point to the same Git ref (version). But that does not matter too much to me, as long as Go Modules are happy.

Also, no rush.

A little digression, but you have a little unusual project structure vs major versions. I suspect it would be easier to navigate and maintain if you just kept all versions in the root and just incremented in `go.mod` (and possibly also created a new default branch), but up to you.

**Comment by bep** [comment]
Bump; could you also have a look at #63 ... which is a blocker for pulling this library into Hugo. Thanks!

**Comment by dsoprea** [comment]
Sure. I'll do it in the next couple of days. Sorry for the delay. This feel off my radar. Plus, it won't be enough to update this project, but also the constellation of tools and format-specific integrations that I've written against it, which will then affect even more people. I'll likely put a note in each project's README out of an abundance of caution.

**Comment by marang** [comment]
hey, looking forward to have working exif lib in hugo soon.

**Comment by dsoprea** [comment]
Done. Pushed v3.0.1 .

**Comment by dsoprea** [comment]
@bep We'll consider this if we ever release v4.

https://github.com/dsoprea/go-exif/issues/62#issuecomment-881867613
