### ISSUE TITLE
Use of panic when we could be passing along the error

### ISSUE THREAD

**Issue by june-remind101** [dsoprea/go-exif#64]
This module and the image format specific modules for it seem to panic on many errors that could be passed down. As it stands, using this library in a service means a needless service restart.

Any objection to replacing many of these panics with returning the error?

**Comment by dsoprea** [comment]
It's a pattern. The defer-recovers at the tops of almost every function will catch and returns them. It shouldn't be disruptive. At any rate, using recovers at the service level will keep it from interrupting anything.

https://blog.golang.org/defer-panic-and-recover
