### ISSUE TITLE
can't read EXIF 0220 or EXIF 0221 version GPS information

### ISSUE THREAD

**Issue by daiyudong** [dsoprea/go-exif#68]
can't read EXIF 0220 or EXIF 0221 version GPS informatio
![123](https://user-images.githubusercontent.com/42144625/156129666-285a708b-6672-4392-a2b3-ad06f4c2c457.jpg)
n

**Comment by dsoprea** [comment]
Why did you end-up closing this?

**Comment by cuizhipeng326** [comment]
> Why did you end-up closing this?

This bug encountered in my parsing jpg image from XiaoMi series mobile phones recently. I need some help about this issue.
![IMG_20240325_210750](https://github.com/dsoprea/go-exif/assets/70935838/a26d7fbc-feaf-4130-ba61-bded275ead42)
Attachment is the photo took by one of XiaoMi mobile phone. I can't parse the gps info by using exiftool or go-exif.
Please have a try and wish you can figure out this problem.

**Comment by cuizhipeng326** [comment]
> > Why did you end-up closing this?
> 
> This bug encountered in my parsing jpg image from XiaoMi series mobile phones recently. I need some help about this issue. ![IMG_20240325_210750](https://private-user-images.githubusercontent.com/70935838/316871805-a26d7fbc-feaf-4130-ba61-bded275ead42.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTA0MjgsIm5iZiI6MTcxMTYxMDEyOCwicGF0aCI6Ii83MDkzNTgzOC8zMTY4NzE4MDUtYTI2ZDdmYmMtZmVhZi00MTMwLWJhNjEtYmRlZDI3NWVhZDQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA3MTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNDYzMWY2NjFhYzZhM2ZlZGRmNDdkYjUzMDAwZTcyMDY3N2VjZTA2NWMxYWFjMTU2MzA2NmVjMmQ4MGI3N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vs9PtcqG2GJshn-pKB7_0-tybRErQdGW4J8FVmc5zkA) Attachment is the photo took by one of XiaoMi mobile phone. I can't parse the gps info by using exiftool or go-exif. Please have a try and wish you can figure out this problem.

Figured it out: the gps info of exif in photos upload from Xiaomi mobile phone had been cleared by Xiaomi MiUI os. So we need to find a correct way to get the raw photo without any edition from mobile phone.
