### ISSUE TITLE
How do you set an image.Image DPI?

### ISSUE THREAD

**Issue by Xeoncross** [dsoprea/go-exif#78]
So far I have the following that creates an entirely new image.Image from the binary data. Is there someway to avoid creating the image again and simply update the images data? In the following I'm working with an instance of a image.RGBA, but the same question goes for a Gray, CMYK, or draw.Image.

```

func SetDPI(img *image.RGBA, dpi uint32) error {
	jmp := jpegstructure.NewJpegMediaParser()

	var buf bytes.Buffer
	err := jpeg.Encode(&buf, img, nil)
	if err != nil {
		return err
	}

	intfc, err := jmp.ParseBytes(buf.Bytes())
	if err != nil {
		return err
	}

	sl := intfc.(*jpegstructure.SegmentList)

	// Make sure we don't start out with EXIF data.
	wasDropped, err := sl.DropExif()
	if err != nil {
		return err
	}

	if !wasDropped {
		return errors.New("Expected the EXIF segment to be dropped, but it wasn't.")
	}

	im := exif2.NewIfdMapping()

	err = exif2.LoadStandardIfds(im)
	if err != nil {
		return err
	}

	ti := exif2.NewTagIndex()
	rootIb := exif2.NewIfdBuilder(im, ti, exifcommon.IfdPathStandard, exifcommon.EncodeDefaultByteOrder)

	err = rootIb.AddStandardWithName("XResolution", []exifcommon.Rational{{Numerator: dpi, Denominator: uint32(1)}})
	if err != nil {
		return err
	}

	err = rootIb.AddStandardWithName("YResolution", []exifcommon.Rational{{Numerator: dpi, Denominator: uint32(1)}})
	if err != nil {
		return err
	}

	err = sl.SetExif(rootIb)
	if err != nil {
		return err
	}

	b := new(bytes.Buffer)
	err = sl.Write(b)
	if err != nil {
		return err
	}

	img2, err := jpeg.Decode(b)
	if err != nil {
		return err
	}

	// Already RGBA?
	if rgba, ok := img2.(*image.RGBA); ok {
		*img = *rgba
	} else {
		return errors.New("expected image.RGBA")
	}

	return nil
}
```

(Note: I haven't tested the above code, I just wrote it based on the API and examples I saw, but should work even if it needs slight tweaking of the img pointers)

**Comment by dsoprea** [comment]
No. The binary data would shift around it unless you've specifically
preallocated those segments/chunks [where the EXIF blob lives] in the
images to be sufficiently large (such as setting them to 500K of NULs and
can guarantee that your EXIF blobs will always be smaller) for some reason.

**Comment by dsoprea** [comment]
Are you having some issue with your code? Your subject and your message don't line-up.

**Comment by Xeoncross** [comment]
Sorry, I guess I was asking if there was a better way to set EXIF data without cloning the entire image encoding data. It would be nice if I could generate an image.Image in Go and then set the EXIF without having to encoded it to bytes, then read in the data, then add the DPI (or other EXIF chunks) and then finally re-decode the image bytes back into an image.Image.

**Comment by dsoprea** [comment]
Not really. Heuristically, you can build the updated EXIF blob yourself, and, if it's smaller, just write it directly to the image at the original offset. There will be cruft at the end that shouldn't matter. You might want to write zeros over that just to simplify any theoretical, future debugging (in the interesting of not leaving arbitrary, non-NUL data to confuse those that come after you).
