### ISSUE TITLE
Writer sample codes

### ISSUE THREAD

**Issue by leslie-qiwa** [dsoprea/go-exif#9]
Can you please provide one sample code for writer? I'm trying to use your tool to put EXIF into thumbnail pictures. 

Thanks

**Comment by dsoprea** [comment]
My bad. This should get you going:

```

**Comment by leslie-qiwa** [comment]
Thanks for the detail example. Just wonder how I can write it into one JPEG file. Directly append? I saw you have one repo `https://github.com/dsoprea/go-jpeg-image-structure`, but it only has reader as well.

**Comment by dsoprea** [comment]
EXIF is something that is image-agnostic. From the perspective of this project, it becomes your responsibility to extract the EXIF from the specific image and update it back if it needs to be changed. Please post an issue at 'go-jpeg-image-structure' and I'll explain how to do it.

**Comment by leslie-qiwa** [comment]
That makes sense. Thanks for the great work. 

https://github.com/dsoprea/go-jpeg-image-structure/issues/1
